import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import Image from 'next/image';
import Cards from "./Cards";
import Footer from "./Footer";
import PartOne from "./PartOne";
import PartTwo from "./PartTwo";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ARMCHAIR-MARKET</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <div className={styles.header_background}>
              <div className={styles.main_conteiner}>
                  <Link href="/" passHref>
                      <div>
                          <div>
                            <Image src="/img/logo-image.png" className={styles.logo} alt="logo market" width="460px" height="170px" />
                          </div>
                      </div>
                  </Link>
                  <div className={styles.mainlink}>
                      <Link href="/faq" passHref>
                          <a name="welcome" className={styles.links_faq}>FAQ</a>
                      </Link>
                          <a className={styles.links_bec} href="#contact">Contact</a>
                      <Link href="/log_in" passHref>
                          <a className={styles.link_log}>Log in</a>
                      </Link>
                  </div>
              </div>
              <div className={styles.menu_box}>
                  <a className={styles.menu_item} href="#about">About US</a>
                  <a className={styles.menu_item} href="#delivery">Delivery</a>
                  <a className={styles.menu_item} href="#market">Market</a>
              </div>
          </div>
          <PartOne />
          <Cards />
          <div id="modal-root"></div>
          <PartTwo />
          <Footer />
      </main>
    </div>
  )
}
